[versions]
agp = "9.0.0"
kotlin = "2.3.10"
browser = "1.9.0"
credentials = "1.5.0"
googleid = "1.2.0"
json = "20251224"
junit = "4.13.2"
kotlinxCoroutinesAndroid = "1.10.2"
lifecycleCommon = "2.10.0"
lifecycleProcess = "2.10.0"
securityCrypto = "1.1.0"
nexus = "2.0.0"

[libraries]
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycleCommon" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
json = { module = "org.json:json", version.ref = "json" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesAndroid" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleProcess" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus" }
